- name: Install common package
  apt:
    name:
      - git
      - mc
      - tree
      - htop
      - net-tools
      - git
      - build-essential
      - vim
      - tmux
      - unzip 
      - apache2-dev
      - sudo
      - apt-transport-https

    state: latest
#update_cache: yes

- name: Create  groups site-2.ru
  group:
    name: site2
    state: present
    
- name: Create user site-2.ru
  user: 
    name: site2
    password: "password"
    update_password: on_create

- name: сreate directory for site-1
  file:
    path=/var/www/{{ vhost1 }}/{{ item }}
    mode=0755
    owner=www-data
    group=www-data
    state=directory
  with_items:
   - doc_root
   - temp
   - sessions
   - logs
  
- name: сreate directory for site-2
  file:
    path=/var/www/{{ vhost2 }}/{{ item }}
    mode=0755
    owner=www-data
    group=www-data
    state=directory
  with_items:
   - doc_root
   - temp
   - sessions
   - logs
